### ISSUE TITLE
Make macOS a release-gated supported platform

### ISSUE THREAD

**Issue by TheGreenCedar** [TheGreenCedar/CodeStory#1046]
Parent: #887
Root: #899
Release: v0.15.0

## Context

CodeStory's macOS implementation is integrated on `dev/codestory-next` at `611052bdaf63b06cdc9f3e68422027956fb3cfee`. The exact-head integration run passed source validation, both Mac package targets, Intel backend policy, and the protected packaged Apple Silicon Metal lifecycle. This issue now owns the release boundary: prove the binaries that actually ship and the plugin/runtime that a fresh Codex installation actually loads.

## Outcome

Ship macOS 15+ as a release-gated platform:

- Apple Silicon uses the checksum-pinned managed Metal backend and opens full packet/search only with live endpoint, process-identity, offload, and embedding-smoke proof.
- Intel macOS supports the native CLI, managed plugin, local graph, and grounding; semantic retrieval requires explicitly allowed CPU operation or a trusted external embedding endpoint and never claims Metal.

## Current evidence

- [Integration run 29352437957](https://github.com/TheGreenCedar/CodeStory/actions/runs/29352437957) passed at `611052bdaf63b06cdc9f3e68422027956fb3cfee`.
- The retained `macos-arm64-metal-proof-0.15.0` artifact proves cold managed Metal, 13/13 layer offload, verified GPU proof, warm PID reuse, dead-endpoint blocking, repair recovery, successful packet/search, managed plugin convergence, and proof-owned cleanup.
- The macOS x64 artifacts prove package execution, plugin/local-grounding operation, actionable default backend failure, and explicitly labelled CPU/external operation without a Metal claim.
- The protected `macos-release-signing` environment contains all six required Developer ID and App Store Connect secret names. Credential validity, Apple acceptance, and published-asset identity remain unproved until the main release runs.

## Acceptance criteria

- [ ] The default-concurrency CLI suite passes twice on the final candidate, with a retained before/after fingerprint proving no writes to `~/Library/Caches/dev.codestory.codestory`.
- [x] Regressions cover dynamic agent ports, avoided refreshes, dead-endpoint readiness blocking, Darwin process-start matching/PID reuse, and test-cache containment.
- [ ] The final exact-head source manifest records formatting, locked workspace check/test, all-target/all-feature clippy, plugin and setup self-tests, indexer fidelity/language suites, runtime retrieval evaluation, and repo-scale stats.
- [x] Packaged Apple Silicon proof covers cold/warm managed Metal, verified GPU proof, PID reuse, packet/search, endpoint-death blocking, repair recovery, and proof-owned cleanup from an isolated cache.
- [x] macOS x64 proves package/plugin/local-graph operation, actionable default backend failure, and correctly labelled explicit CPU/external operation without a Metal claim.
- [ ] A two-phase protected-host bundle proves readiness and recovery across a real macOS reboot; the single-job Metal lifecycle is not reboot evidence.
- [ ] Both published Mac assets are Developer ID-signed and notarized; quarantined extraction passes checksum, `codesign`, `spctl`, version, help, and native execution checks.
- [ ] A real fresh Codex install resolves the marketplace plugin, reports the expected installed CLI/runtime version and digest, and passes live status, grounding, packet/search, and restart acceptance.
- [ ] The final v0.15 changelog and support/troubleshooting/testing docs describe the delivered behavior, upgrade choices, and proof boundaries without implementation-history noise.

## Verification

- Exact-head source and repo-scale acceptance
- Main-only signed/notarized six-asset release workflow
- Protected Apple Silicon Metal lifecycle and separate two-phase reboot bundle
- Six post-publish asset cells, including quarantined Gatekeeper checks for both Mac architectures
- Marketplace update plus fresh Codex installed-runtime and live retrieval readback

## Dependencies and proof boundary

- Final changelog polish: #1132
- Release signing and notarization run only from `main`; PR and integration candidates remain unsigned.
- Source/package evidence does not prove published asset identity, marketplace propagation, or the installed runtime.
- Close #887 only after its published v0.15 restart/packet/search readback passes; close this issue only after every unchecked release item above is retained.

## Non-goals

- Do not claim managed Metal parity on Intel macOS.
- Do not add Cursor or Claude Code as additional macOS release gates.
- Do not weaken accelerator-required readiness or trust a persisted full manifest without live endpoint and identity-bound GPU proof.
- Do not delete user cache state without CodeStory proof ownership.

**Comment by TheGreenCedar** [comment]
## Open-PR overlap audit — 2026-07-12

This child remains a distinct macOS contract. I compared the implementation worktree against every currently open CodeStory PR and fast-forwarded `codex/macos-support` to `dev/codestory-next` at `7a6397e24c8ddf438a1120207c0b076a0289cbe8` so it retains the newly integrated #1042 and #1045 work.

| Open PR | Owned contract | Relationship to #1046 |
| --- | --- | --- |
| #1038 | Prior-version managed CLI upgrade convergence | Related harness/plugin files, but no duplicated behavior. #1046 owns Metal endpoint death/recovery and Intel CPU/external labelling. Preserve both when #1038 integrates. |
| #1041 | Broker and repair ownership migration to project identity v3 | Related broker/path files, but no duplicated behavior. #1046 owns early test-root activation, selected-runtime liveness, and Darwin executable/args/start-time identity. Rebase and re-run broker tests after #1041 integrates. |
| #1044 | Linux glibc 2.31 build/runtime qualification | Related package workflow/policy/docs files only. #1046 does not implement or claim a Linux baseline. Preserve the pinned Linux cells when #1044 integrates. |

No current open PR owns the POSIX worktree setup, macOS dual-architecture workspace gates, Developer ID/notarization gates, Intel runtime-policy proof, protected Apple Silicon lifecycle workflow, or Darwin native-session survival fix in this issue.

Non-claim: same-file conflict freedom is not proven until these branches integrate. Exact-head verification must run again after the final rebase; this audit only establishes that the product contracts are not duplicates.

**Comment by TheGreenCedar** [comment]
## Implementation status after base catch-up — 2026-07-12

`codex/macos-support` is now based exactly on `dev/codestory-next` at `0c2d830db61f`. The base already includes managed CLI upgrade convergence (#1038), Linux x64 glibc 2.31 qualification (#1044), lexical schema migration (#1047), and broker/repair project-identity v3 (#1041); the macOS work was adapted to preserve each contract.

### Overlap

There are currently **no open CodeStory PRs**, so this is not duplicating an active implementation lane. Related open issues remain complementary:

- #887 is the Apple Silicon endpoint-survival acceptance report this work must satisfy with packaged evidence.
- #884 is the broader durable cross-process broker contract; #1046 supplies the macOS process-identity, reuse, and dead-endpoint behavior.
- #897 owns automatic grounding convergence, while #1032, #1034, and #1035 own later identity-rollout work. This lane consumes those contracts without closing them.

### Implemented

- Test sidecar state is selected before the first cache lookup, with a source-level guard against bypassing the gateway.
- Agent bootstrap and health checks use the selected dynamic endpoint. Darwin native reuse requires matching executable, exact arguments, and locale-stable process-start identity.
- A persisted `full` manifest cannot keep packet/search open after endpoint death or invalid GPU/runtime identity; repair guidance remains actionable.
- Managed Metal survives the launching CLI, is safely reused across MCP restarts, and does not spawn duplicate servers.
- Codex worktree setup now has a Node dispatcher and POSIX implementation. macOS arm64/x64 source/package gates, Developer ID/notarization/Gatekeeper gates, Intel no-Metal policy proof, and protected Apple Silicon lifecycle proof are defined.

### Exact-head proof

- Packaged Apple Silicon lifecycle passed locally on an Apple M5 from an isolated cache: checksum-pinned install, managed `native_spawned` Metal, 13/13 layer offload, bounded embedding smoke, `gpu_proof=verified`, `retrieval_mode=full`, PID reuse, packet/search success, endpoint-death blocking, repair recovery, edge cases, and proof-owned cleanup.
- The default-concurrency CLI suite passed twice; `cargo test --workspace --locked`, workspace check, format, and all-target/all-feature clippy passed.
- Plugin static tests, POSIX setup tests, retrieval/worktree setup self-tests, packaged proof self-test, release package self-test, workflow policy, docs links, `actionlint`, release metadata, and shell syntax passed.
- The mandatory repo-scale full-sidecar stats run passed and was appended to the stats log: 147,643 nodes, 123,146 edges, 19,187 symbol documents, and 1,004 dense projections.
- Test/proof-owned processes, containers, ports, and temporary cache state were removed. The real macOS cache fingerprint remained unchanged.

### Residual release gates

- Provision the Developer ID and App Store Connect notarization credentials in the protected release environment, then verify the signed/notarized arm64 and x64 assets.
- Run native Intel macOS acceptance; Apple Silicon cannot substitute for x64 CPU/external-backend proof.
- Run the protected exact-candidate Metal workflow, post-publish quarantine/Gatekeeper checks, and a real fresh Codex marketplace install/readback.
- The inventoried abandoned real-cache test namespaces remain untouched pending narrowly scoped cleanup approval.

The implementation is ready for review, but #887 and #1046 should remain open until the signed release-candidate, Intel, and installed-runtime gates pass.

**Comment by TheGreenCedar** [comment]
## Apple Silicon implementation checkpoint — 2026-07-13

The current unstaged tree is based exactly on `dev/codestory-next` at `0c2d830db61f` and now passes the packaged Apple Silicon lifecycle locally. GitHub currently reports no open CodeStory PRs, so this is not duplicating an active implementation lane.

### Simplification

The macOS contracts remain, but the defensive test matrix has been cut substantially:

- CLI unit tests: 321 → 291.
- Retrieval unit tests: 372 → 355.
- Packaged-proof `self_test()`: 1,244 → 527 lines.
- Removed the hardware proof's redundant bootstrap/index/status preflight; `ready --repair` already owns bootstrap, Metal verification, indexing, and final readiness.

The retained coverage focuses on cache containment, dynamic endpoints, Compose rollback/ownership, Darwin executable/arguments/start identity, PID reuse, dead-endpoint blocking, borrower safety, and atomic publication.

### Exact packaged proof

The packaged arm64 CLI passed from an isolated cache and a project path containing spaces and Unicode:

- Managed `llama-server` launched from the checksum-pinned cache and offloaded 13/13 layers to Metal.
- `ready --goal agent --repair` reached `retrieval_mode=full`, `gpu_proof=verified`, meaningful accelerator work, and a 14 ms embedding smoke at the selected dynamic endpoint.
- Warm readiness reused PID 41888 with matching executable, argv, and Darwin process-start identity.
- Killing that endpoint produced `repair_retrieval` and blocked agent readiness.
- Repair recovered on PID 53793 with verified GPU proof.
- Search returned indexed symbol hits; context, sufficient sidecar packet, CLI stdio, and packaged plugin stdio all passed.
- Proof-owned PIDs exited, all three ports became unreachable, Docker resources were absent, and the isolated proof root was removed.

Post-pruning checks are also green: fmt, locked workspace check/test, all-target/all-feature clippy, 291 CLI tests, 355 retrieval tests, indexer fidelity/language suites, packaged-proof self-test, plugin static tests, POSIX setup tests/self-tests, retrieval setup self-test, workflow policy, docs links, `actionlint`, shell syntax, and diff checks.

### Remaining release gates

Keep #1046 and #887 open until the protected Developer ID/notarization secrets are provisioned, the protected Apple Silicon workflow runs on its release runner, native Intel acceptance passes, published assets pass signed/notarized quarantine checks, and a fresh Codex marketplace install is verified.

**Comment by TheGreenCedar** [comment]
## Draft PR opened

PR #1048 is open against `dev/codestory-next` from `codex/macos-support` at `a2e3423`:

https://github.com/TheGreenCedar/CodeStory/pull/1048

The initial CI run exposed two proof-harness contract mismatches: Linux self-test roots were outside `$RUNNER_TEMP`, and the Intel external-CPU proof expected `allow_cpu` instead of the emitted `cpu_allowed` wire value. Both are fixed in `a2e3423`; the replacement plugin-static and macOS setup workflows are green, while the longer Rust and packaged-platform jobs continue.

The PR closes #1046 and references #887. Project linkage is still pending because the current GitHub CLI token lacks Projects scope.

**Comment by TheGreenCedar** [comment]
## Coordinator checkpoint — 2026-07-13

PR #1048 is the active macOS support lane at exact head `a2e342381bea1ff73206dadba6565f911d556779`, two commits ahead of `dev/codestory-next` at `0c2d830db61fc38eb818cc6bc6c033b75eaadb5e`.

The current decision is whether the draft is exact-head clean and ready for external Apple/Intel release proof. Three isolated read-only lanes are running in detached worktrees; the coordinator retains all integration and release decisions.

| Lane | Worktree | Scope | Required proof |
| --- | --- | --- | --- |
| `/root/pr_metadata` | `/Users/albert/Developer/CodeStory-worktrees/macos-pr1048-workspace-ci` | Diagnose failed Linux `workspace cargo checks` | Complete job log, root cause, smallest safe patch, serialized verification |
| `/root/stats_gate_inspect` | `/Users/albert/Developer/CodeStory-worktrees/macos-pr1048-arm-ci` | Diagnose failed `macOS workspace cargo checks (macos-arm64)` | Complete job log, runner/code classification, smallest safe patch |
| `/root/pr_scope_review` | `/Users/albert/Developer/CodeStory-worktrees/macos-pr1048-review` | Independent exact-head correctness and simplification review | File/line findings, risk classification, merge disposition |

Integration rule: diagnose and review in parallel; apply only concrete fixes onto `codex/macos-support`, serialize Cargo verification, push one coherent follow-up, then re-review the new exact head.

Non-claims: passing packaged build jobs does not yet prove protected Developer ID/notarization, Apple Silicon hosted Metal lifecycle, native Intel acceptance, published quarantined assets, or a fresh marketplace install.

**Comment by TheGreenCedar** [comment]
PR #1048 is updated at exact head `7110d5628eaead6324dc61fa9c69f80de580aab7`.

Review remediation now preserves the `retrieval_mode=full` manifest classification while requiring live endpoint and identity-bound GPU proof for packet/search, serializes same-project Compose ownership through caller cleanup, removes the two low-value test assertions identified by simplification review, and fixes deterministic cancellation plus cross-platform clippy failures.

Final local proof passed: locked workspace check/test, all-target/all-feature clippy, packaged-proof and POSIX setup self-tests, workflow/doc/plugin gates, and the repository-scale full-sidecar run (148,383 nodes, 123,783 edges, 19,246 symbol documents, 1,006 dense projections). Hosted CI is running on the pushed head.

Independent work remains active in isolated worktrees for #911 and #1039; neither lane is coupled to this PR.

**Comment by TheGreenCedar** [comment]
## Source merged; protected release proof is active

The source integration is complete: PR #1048 merged into `dev/codestory-next` as `72c674e5484b9175214846be3dcc7333105d200b`, with a merge tree identical to the fully tested head. All 19 substantive exact-head checks passed; the sole skipped cell was the intentional Windows missing-manifest negative path. Child #1049 closed with the merge.

Release closeout remains open here and in #887. Current credential/hardware progress:

- Apple issued `Developer ID Application: Albert Najjar (PKUJNR8D6F)`, valid through July 2031.
- A disposable release CLI copy passed Developer ID hardened-runtime signing, timestamping, strict verification, and Team ID readback locally.
- The protected `macos-release-signing` environment exists with required-reviewer and protected-branch rules; CI-exportable signing and notarization secrets are still being provisioned.
- This Apple Silicon host is being registered for the protected `codestory-metal` runner lane; no hardware workflow has been dispatched yet.

This issue stays open until signed/notarized packaged assets, protected Metal lifecycle evidence, post-publish Gatekeeper checks, and a real fresh Codex marketplace install/readback all pass.

**Comment by TheGreenCedar** [comment]
## Developer ID signing credential is live

The protected `macos-release-signing` environment now contains the exact CI-exportable Developer ID material:

- `APPLE_DEVELOPER_ID_P12_BASE64`
- `APPLE_DEVELOPER_ID_P12_PASSWORD`
- `APPLE_SIGNING_IDENTITY=Developer ID Application: Albert Najjar (PKUJNR8D6F)`

The exported certificate is Apple-issued, valid through July 2031, and its hardened-runtime smoke binary passes strict `codesign` verification with a secure timestamp and Team ID `PKUJNR8D6F`. The protected Apple Silicon runner is also online under the `codestory-metal` label.

Notarization is the remaining credential boundary: `APPLE_NOTARY_KEY_P8_BASE64`, `APPLE_NOTARY_KEY_ID`, and `APPLE_NOTARY_ISSUER_ID` still require an App Store Connect API key. No signed asset will be published until those protected secrets and the exact packaged signing/notarization workflow pass.

**Comment by TheGreenCedar** [comment]
Developer ID signing is now proved against the actual local `codestory-cli 0.14.3` release binary, not only a synthetic smoke executable.

- identity: `Developer ID Application: Albert Najjar (PKUJNR8D6F)`
- `codesign --verify --strict`: passed
- hardened runtime: present
- secure Apple timestamp: present
- certificate chain: Developer ID Application -> Developer ID Certification Authority -> Apple Root CA
- TeamIdentifier: `PKUJNR8D6F`
- signed binary execution: `codestory-cli 0.14.3`

The validated exportable P12 and signing identity remain installed in the protected `macos-release-signing` GitHub environment. Notarization is still the remaining credential boundary because no local `notarytool` keychain profile or App Store Connect API-key secret exists yet.

**Comment by TheGreenCedar** [comment]
Developer ID credential proof is now complete for the signing half of the release contract.

- Apple-issued identity: `Developer ID Application: Albert Najjar (PKUJNR8D6F)`
- Apple Developer ID G2 chain; certificate valid through 2031-07-14
- Protected `macos-release-signing` environment has the encrypted P12, P12 password, and signing identity secrets
- Re-imported the exported P12 into a fresh temporary keychain, then signed the actual `codestory-cli 0.14.3` binary with hardened runtime and a secure timestamp
- `codesign --verify --strict` passed; the signature reports the Developer ID chain and `TeamIdentifier=PKUJNR8D6F`; the signed binary executes successfully
- Temporary proof keychain and binary were removed after the check; the permission-locked export remains only until hosted CI proof succeeds

Notarization remains fail-closed until the three protected App Store Connect API-key secrets are provisioned. No unsigned Mac release can publish through the current workflow.

**Comment by TheGreenCedar** [comment]
The exact merged remediation head `611052bdaf63b06cdc9f3e68422027956fb3cfee` passed [integration run 29352437957](https://github.com/TheGreenCedar/CodeStory/actions/runs/29352437957).

Mac acceptance covered locked arm64 and x64 packaged builds, Intel CPU/external-backend policy, live full-sidecar repo-scale stats, and the protected packaged Apple Silicon Metal lifecycle: cold start, warm PID reuse, endpoint death, fail-closed readiness, repair, packet/search, managed plugin convergence, and proof-owned cleanup.

This proves the branch and packaged unsigned artifacts. The issue remains open for the main-release boundary only: Developer ID signing/notarization, post-publish quarantined extraction and Gatekeeper checks, marketplace propagation, and a real fresh Codex installed-runtime/version readback. Apple credentials were intentionally not used in PR or integration workflows.

**Comment by TheGreenCedar** [comment]
The v0.15.0 macOS release boundary is now proven.

- Main/dev exact head: `85a877e1f0bc9986d203b09efe70f2956fb5b32e`.
- Complete release run: https://github.com/TheGreenCedar/CodeStory/actions/runs/29363386284
- Published release: https://github.com/TheGreenCedar/CodeStory/releases/tag/v0.15.0
- arm64 and x64 assets passed Developer ID signing, hardened runtime, secure timestamp, Apple notarization, quarantined native execution, checksum, version/help, and post-publish download smoke.
- Protected Apple Silicon package proof passed cold/warm Metal, verified GPU proof, PID reuse, dead-endpoint blocking, repair recovery, packet/search, plugin convergence, and cleanup.
- Intel package proof passed native CLI/plugin/local graph plus actionable default backend failure and explicit CPU/external labeling without a Metal claim.
- Fresh local Codex marketplace install provisioned plugin and managed CLI 0.15.0 from the published arm64 asset. The installed binary is signed by `Developer ID Application: Albert Najjar (PKUJNR8D6F)`, uses hardened runtime, and satisfies its designated requirement.
- Local M5 repair reached full retrieval with verified Metal and a 7 ms embedding smoke. Full search succeeded; packet returned sufficient evidence with 13 citations and no gaps. Plugin restart reused the same managed version and digest.
- Marketplace pointer PR: https://github.com/TheGreenCedar/AgentPluginMarketplace/pull/10

This issue remains open only for its two explicit proof-only items that were deliberately not repeated during the expedited release: a final-head default-concurrency/cache-fingerprint source run, and the separate two-phase physical host-reboot bundle. The shipped macOS behavior, published assets, marketplace install, signing/notarization, and live packet/search path are working.
